/* AUTO-GENERATED by scripts/gen-levels.mjs — do not edit. */
import lv001 from '../../levels/level-001.json';
import lv002 from '../../levels/level-002.json';
import lv003 from '../../levels/level-003.json';
import lv004 from '../../levels/level-004.json';
import lv005 from '../../levels/level-005.json';
import lv006 from '../../levels/level-006.json';
import lv007 from '../../levels/level-007.json';
import lv008 from '../../levels/level-008.json';
import lv009 from '../../levels/level-009.json';
import lv010 from '../../levels/level-010.json';
import lv011 from '../../levels/level-011.json';
import lv012 from '../../levels/level-012.json';
import lv013 from '../../levels/level-013.json';
import lv014 from '../../levels/level-014.json';
import lv015 from '../../levels/level-015.json';
import lv016 from '../../levels/level-016.json';
import lv017 from '../../levels/level-017.json';
import lv018 from '../../levels/level-018.json';
import lv019 from '../../levels/level-019.json';
import lv020 from '../../levels/level-020.json';
import lv021 from '../../levels/level-021.json';
import lv022 from '../../levels/level-022.json';
import lv023 from '../../levels/level-023.json';
import lv024 from '../../levels/level-024.json';
import lv025 from '../../levels/level-025.json';
import lv026 from '../../levels/level-026.json';
import lv027 from '../../levels/level-027.json';
import lv028 from '../../levels/level-028.json';
import lv029 from '../../levels/level-029.json';
import lv030 from '../../levels/level-030.json';
import lv031 from '../../levels/level-031.json';
import lv032 from '../../levels/level-032.json';
import lv033 from '../../levels/level-033.json';
import lv034 from '../../levels/level-034.json';
import lv035 from '../../levels/level-035.json';
import lv036 from '../../levels/level-036.json';
import lv037 from '../../levels/level-037.json';
import lv038 from '../../levels/level-038.json';
import lv039 from '../../levels/level-039.json';
import lv040 from '../../levels/level-040.json';
import lv041 from '../../levels/level-041.json';
import lv042 from '../../levels/level-042.json';
import lv043 from '../../levels/level-043.json';
import lv044 from '../../levels/level-044.json';
import lv045 from '../../levels/level-045.json';
import lv046 from '../../levels/level-046.json';
import lv047 from '../../levels/level-047.json';
import lv048 from '../../levels/level-048.json';
import lv049 from '../../levels/level-049.json';
import lv050 from '../../levels/level-050.json';
import lv051 from '../../levels/level-051.json';
import lv052 from '../../levels/level-052.json';
import lv053 from '../../levels/level-053.json';
import lv054 from '../../levels/level-054.json';
import lv055 from '../../levels/level-055.json';
import lv056 from '../../levels/level-056.json';
import lv057 from '../../levels/level-057.json';
import lv058 from '../../levels/level-058.json';
import lv059 from '../../levels/level-059.json';
import lv060 from '../../levels/level-060.json';

export const LEVEL_JSONS: readonly unknown[] = [
  lv001 as unknown,
  lv002 as unknown,
  lv003 as unknown,
  lv004 as unknown,
  lv005 as unknown,
  lv006 as unknown,
  lv007 as unknown,
  lv008 as unknown,
  lv009 as unknown,
  lv010 as unknown,
  lv011 as unknown,
  lv012 as unknown,
  lv013 as unknown,
  lv014 as unknown,
  lv015 as unknown,
  lv016 as unknown,
  lv017 as unknown,
  lv018 as unknown,
  lv019 as unknown,
  lv020 as unknown,
  lv021 as unknown,
  lv022 as unknown,
  lv023 as unknown,
  lv024 as unknown,
  lv025 as unknown,
  lv026 as unknown,
  lv027 as unknown,
  lv028 as unknown,
  lv029 as unknown,
  lv030 as unknown,
  lv031 as unknown,
  lv032 as unknown,
  lv033 as unknown,
  lv034 as unknown,
  lv035 as unknown,
  lv036 as unknown,
  lv037 as unknown,
  lv038 as unknown,
  lv039 as unknown,
  lv040 as unknown,
  lv041 as unknown,
  lv042 as unknown,
  lv043 as unknown,
  lv044 as unknown,
  lv045 as unknown,
  lv046 as unknown,
  lv047 as unknown,
  lv048 as unknown,
  lv049 as unknown,
  lv050 as unknown,
  lv051 as unknown,
  lv052 as unknown,
  lv053 as unknown,
  lv054 as unknown,
  lv055 as unknown,
  lv056 as unknown,
  lv057 as unknown,
  lv058 as unknown,
  lv059 as unknown,
  lv060 as unknown,
];
